service: hello-world
frameworkVersion: "2"

custom:
  stage: dev
  region: us-east-1
  thundra_apikey: <THUNDRA_APIKEY>

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${self:custom.stage}
  region: ${self:custom.region}

functions:
  hello:
    handler: handler.hello
    environment:
      THUNDRA_APIKEY: ${self:custom.thundra_apikey}
